### ISSUE TITLE
Register Now button on single page was globally setup. There might be instances that every single event has different external link. Can this option be added to the individual event post instead?

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Vose-Seminary#34]

**Comment by genesiscebudigital** [comment]
we will confirm it to ricky

**Comment by christiancebudigital** [comment]
Hi Erma,

For this question, I've called Ricky Fang few weeks ago for clarification on the registration button, he mentioned that register now button will be globally set up, as well wait for the client review  on what they want to do with the registration button, hope that answers your question.

Thanks,
Christian
