### ISSUE TITLE
Event style page should be paginated after 10 page/post as per project scope. Currently pagination starts after 5 post

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Vose-Seminary#35]

**Comment by genesiscebudigital** [comment]
ricky said . ,it will paginate to five. , we will update the project scope

**Comment by ermatitan** [comment]
Project scope not updated....
![image](https://cloud.githubusercontent.com/assets/12791909/9057293/a8f2da56-3acb-11e5-8ca1-5375d0640587.png)
