### ISSUE TITLE
Album gallery not centered 

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Vose-Seminary#54]
http://voseseminary.stage.titanweb.com.au/gallery-album/

![gallery album - vose seminary](https://cloud.githubusercontent.com/assets/12791909/8974077/4ac4ddbe-36a0-11e5-92cf-581daa008e16.png)

**Comment by genesiscebudigital** [comment]
there is no psd design for the album

**Comment by ermatitan** [comment]
It doesn't mean that if there is no design, it is not a bug. It is still a bug and it needs to be fix. Thanks

**Comment by ermatitan** [comment]
Hello genesis, it seems that you have aligned centered album itself (which makes the compact and extended album similar) which is another bug. 

What I mean on this issue is that the gallery thumbnails on each gallery should be displayed centered on the content area of the page. Currently, the thumbnails are overlapping with each other.

![image](https://cloud.githubusercontent.com/assets/12791909/9194721/148264b0-4050-11e5-979b-28ce23bfb9c3.png)
