### ISSUE TITLE
Event Sidebar: Related Items width not the same with PSD design.

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Vose-Seminary#55]
![image](https://cloud.githubusercontent.com/assets/12791909/8974352/5f224cf8-36a3-11e5-8341-1065ca7ed9f3.png)

**Comment by genesiscebudigital** [comment]
We just follow the grid of the bootsrap . ,

**Comment by ermatitan** [comment]
If you can't fix this just change the label to won't fix. Thanks
