### ISSUE TITLE
Inner Page  Banner content  text not centered on Samsung Tab 3 portrait view

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Vose-Seminary#56]
![image](https://cloud.githubusercontent.com/assets/12791909/8974487/b8567bb8-36a4-11e5-9dfb-8c098934035a.png)

**Comment by genesiscebudigital** [comment]
the text in the psd is not align center

**Comment by ermatitan** [comment]
As you can see in the screenshot, i have attached a landscape view as a reference. Yes it is not aligned center in PSD design,but as you notice in the landscape view, the spacing between the Enroll Now button is the same with the top margin, thus make it look nicer and centered vertically.

**Comment by ermatitan** [comment]
What i meant with centered vertically is that the space before and after text and the enroll now button is the same. please check on the screenshot. 

![image](https://cloud.githubusercontent.com/assets/12791909/9214591/63abfd1c-40d2-11e5-97f0-f0c8d4f1d4bd.png)
