### ISSUE TITLE
There are 2 event page listing with the same content from the Event ACF post. Is this correct? 

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Vose-Seminary#57]
Home page > Latest Events > View All will lead to this URL : http://voseseminary.stage.titanweb.com.au/events/

Lead-Ins > Leadership Events > will lead to this URL: 
http://voseseminary.stage.titanweb.com.au/leadership-events/

**Comment by genesiscebudigital** [comment]
that is a template . , they cam put event in everypage they want . , most of the design are templates

**Comment by ermatitan** [comment]
Yes it is a template, but for SEO wise, content redundancy is not good with different URL's. There should be 1 URL for each content.
