### ISSUE TITLE
Related Items side bar should have an active state when hover on both Event and News page

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Vose-Seminary#58]
![image](https://cloud.githubusercontent.com/assets/12791909/8974558/ab1afffe-36a5-11e5-9056-abbfc6a5e791.png)

**Comment by genesiscebudigital** [comment]
The designer did not pud active state in the psd

**Comment by ermatitan** [comment]
That is why this issue was labeled as "enhancement"
