### ISSUE TITLE
Sidebar spacing/padding not the same with PSD Design

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Vose-Seminary#71]
![image](https://cloud.githubusercontent.com/assets/12791909/9056472/c1a0c62c-3ac5-11e5-96de-d2a3df9b7de1.png)

**Comment by genesiscebudigital** [comment]
I just follow the bootsrap grid . , this is not a big isue

**Comment by ermatitan** [comment]
What i meant in this issue is the height between items. It's not a big issue, you can just adjust the padding on each item.
