### ISSUE TITLE
Who We Are : Page title and URL (permalink) did not match

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Vose-Seminary#76]
Note: Permalink not available in the backend.

![image](https://cloud.githubusercontent.com/assets/12791909/9079120/3eab6614-3b79-11e5-8946-1a6cf9ec0e66.png)

**Comment by genesiscebudigital** [comment]
the menu name is about us . ,

**Comment by ermatitan** [comment]
design issue
