### ISSUE TITLE
Related Items sidebar should not be displayed if there is no value added in the page repeater

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Vose-Seminary#77]
Layout Used: Link Style

![image](https://cloud.githubusercontent.com/assets/12791909/9079427/9097102e-3b7c-11e5-8dfd-7a2dc069b27d.png)

**Comment by genesiscebudigital** [comment]
you can use another template if you don't add sidebar

**Comment by ermatitan** [comment]
You can add a required fields on the backend for this layout to prevent this hanging label to show up on the front-end. Thanks
