### ISSUE TITLE
Event Page listing : Event title font weight should be set to 400/Normal, font family is just regular

### ISSUE THREAD

**Issue by ermatitan** [titan-cebu/Vose-Seminary#89]
![image](https://cloud.githubusercontent.com/assets/12791909/9081084/f877b630-3b8b-11e5-88a2-29554fd1ff85.png)

**Comment by genesiscebudigital** [comment]
the default font is 400   , that is 400 already. , the raleway-regular is the name of the font

**Comment by ermatitan** [comment]
Please check the attach screenshot. Font weight is 500, it should be 400. 
See the link below for the difference in font weight
https://www.google.com/fonts/specimen/Raleway
